(function () {
  "use strict";

  var CARD_W = 1060;
  var CARD_H = 615;
  var MARGIN = 115;
  var PAD = 32;
  var CANVAS_W = CARD_W + MARGIN * 2;
  var CANVAS_H = CARD_H + MARGIN * 2;
  var RENDER_SCALE = 1.1;
  var TYPEWRITER_FONT = '"Special Elite", monospace';
  var HANDWRITTEN_FONT = '"Kalam", cursive';

  // layoutTextZones() geometry — the stamp box, and the vertical rhythm of the
  // subject/message/signature/postscript column that sits beside it.
  var STAMP_W = 104;
  var STAMP_H = 126;
  var STAMP_TO_MESSAGE_GAP = 26;
  var SUBJECT_HEIGHT = 20;
  var SUBJECT_BASELINE_OFFSET = 14;
  var SUBJECT_GAP = 26;
  var MESSAGE_BOTTOM_MARGIN = 44;
  var MESSAGE_LINE_HEIGHT = 23;
  var MESSAGE_FONT_SIZE = 19;
  var MESSAGE_BOOKEND_FONT_SIZE = 21;
  var POSTSCRIPT_FONT_SIZE = 16;
  var POSTSCRIPT_LINE_HEIGHT = 20;
  var FOOTER_HEIGHT = 30;
  var MESSAGE_RECT_TOP_PAD = 16;
  var MESSAGE_RECT_BOTTOM_PAD = 6;

  var CARD_BORDER_DARKEN = 0.22;
  var GHOST_STACK_MAX_OFFSET = 6;

  window.PostcardConfig = {
    CARD_W: CARD_W,
    CARD_H: CARD_H,
    MARGIN: MARGIN,
    PAD: PAD,
    CANVAS_W: CANVAS_W,
    CANVAS_H: CANVAS_H,
    RENDER_SCALE: RENDER_SCALE,
    TYPEWRITER_FONT: TYPEWRITER_FONT,
    HANDWRITTEN_FONT: HANDWRITTEN_FONT,
    STAMP_W: STAMP_W,
    STAMP_H: STAMP_H,
    STAMP_TO_MESSAGE_GAP: STAMP_TO_MESSAGE_GAP,
    SUBJECT_HEIGHT: SUBJECT_HEIGHT,
    SUBJECT_BASELINE_OFFSET: SUBJECT_BASELINE_OFFSET,
    SUBJECT_GAP: SUBJECT_GAP,
    MESSAGE_BOTTOM_MARGIN: MESSAGE_BOTTOM_MARGIN,
    MESSAGE_LINE_HEIGHT: MESSAGE_LINE_HEIGHT,
    MESSAGE_FONT_SIZE: MESSAGE_FONT_SIZE,
    MESSAGE_BOOKEND_FONT_SIZE: MESSAGE_BOOKEND_FONT_SIZE,
    POSTSCRIPT_FONT_SIZE: POSTSCRIPT_FONT_SIZE,
    POSTSCRIPT_LINE_HEIGHT: POSTSCRIPT_LINE_HEIGHT,
    FOOTER_HEIGHT: FOOTER_HEIGHT,
    MESSAGE_RECT_TOP_PAD: MESSAGE_RECT_TOP_PAD,
    MESSAGE_RECT_BOTTOM_PAD: MESSAGE_RECT_BOTTOM_PAD,
    CARD_BORDER_DARKEN: CARD_BORDER_DARKEN,
    GHOST_STACK_MAX_OFFSET: GHOST_STACK_MAX_OFFSET
  };
})();
